#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE_ROOT = SCRIPT_DIR.parent

CODEX_DIR = WORKSPACE_ROOT / ".codex" / "agents"
CLAUDE_DIR = WORKSPACE_ROOT / ".claude" / "agents"

GENERATED_NOTICE = (
    "<!-- GENERATED FROM .codex/agents BY scripts/sync_agents.py. "
    "DO NOT EDIT THIS FILE DIRECTLY. -->"
)

# Canonical developer_instructions must describe the logical Moda agent, not
# Codex-specific execution behaviour. General references to Codex are allowed
# when discussing supported runtimes, file locations, or Claude/Codex parity.
FORBIDDEN_RUNTIME_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"(?im)^\s*executor\s*:\s*codex\s*$"),
        "hard-coded `executor: codex`; use the current execution runtime instead",
    ),
    (
        re.compile(r"(?i)\bin this codex agent definition\b"),
        "Codex-specific behavioural wording",
    ),
    (
        re.compile(r"(?i)\bin this codex runtime\b"),
        "Codex-specific behavioural wording",
    ),
    (
        re.compile(r"(?i)\bthis codex runtime\b"),
        "Codex-specific behavioural wording",
    ),
    (
        re.compile(r"(?i)\bcodex must\b"),
        "behaviour assigned specifically to Codex rather than the logical agent",
    ),
    (
        re.compile(r"(?i)\bcodex should\b"),
        "behaviour assigned specifically to Codex rather than the logical agent",
    ),
)


@dataclass(frozen=True)
class AgentDefinition:
    source_path: Path
    name: str
    description: str
    instructions: str

    @property
    def claude_filename(self) -> str:
        return f"{self.source_path.stem}.agent.md"

    @property
    def claude_path(self) -> Path:
        return CLAUDE_DIR / self.claude_filename


class SyncError(Exception):
    """Raised when canonical agent definitions cannot be safely synchronized."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Claude agent definitions from canonical Codex TOML files."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write files. Exit non-zero if generated Claude files are "
            "missing or stale."
        ),
    )
    parser.add_argument(
        "--agent",
        action="append",
        default=[],
        metavar="NAME",
        help=(
            "Sync/check only the named logical agent. May be supplied multiple "
            "times, for example: --agent moda_app --agent moda_background."
        ),
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help=(
            "Remove generated Claude agent files that no longer have a matching "
            "Codex TOML source. Not allowed together with --agent."
        ),
    )
    return parser.parse_args()


def validate_runtime_neutrality(*, toml_path: Path, instructions: str) -> None:
    violations: list[str] = []

    for pattern, explanation in FORBIDDEN_RUNTIME_PATTERNS:
        match = pattern.search(instructions)
        if not match:
            continue

        line_number = instructions.count("\n", 0, match.start()) + 1
        excerpt = match.group(0).strip().replace("\n", " ")
        violations.append(
            f"line {line_number}: {explanation}: {excerpt!r}"
        )

    if violations:
        formatted = "\n".join(f"  - {item}" for item in violations)
        raise SyncError(
            f"{toml_path}: canonical developer instructions must be "
            f"runtime-neutral:\n{formatted}"
        )


def load_agent(toml_path: Path) -> AgentDefinition:
    try:
        with toml_path.open("rb") as f:
            data = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise SyncError(f"{toml_path}: invalid TOML: {exc}") from exc

    required = ("name", "description", "developer_instructions")
    missing = [key for key in required if key not in data]
    if missing:
        raise SyncError(
            f"{toml_path}: missing required field(s): {', '.join(missing)}"
        )

    name = data["name"]
    description = data["description"]
    instructions = data["developer_instructions"]

    if not isinstance(name, str) or not name.strip():
        raise SyncError(f"{toml_path}: `name` must be a non-empty string")

    if not isinstance(description, str):
        raise SyncError(f"{toml_path}: `description` must be a string")

    if not isinstance(instructions, str) or not instructions.strip():
        raise SyncError(
            f"{toml_path}: `developer_instructions` must be a non-empty string"
        )

    expected_name = toml_path.stem
    if name != expected_name:
        raise SyncError(
            f"{toml_path}: `name` {name!r} must match filename stem "
            f"{expected_name!r}"
        )

    normalized_instructions = instructions.replace("\r\n", "\n").strip()

    validate_runtime_neutrality(
        toml_path=toml_path,
        instructions=normalized_instructions,
    )

    return AgentDefinition(
        source_path=toml_path,
        name=name,
        description=description.strip(),
        instructions=normalized_instructions,
    )


def render_claude(agent: AgentDefinition) -> str:
    # json.dumps emits safely quoted strings that are also valid YAML scalars.
    return (
        "---\n"
        f"name: {json.dumps(agent.name)}\n"
        f"description: {json.dumps(agent.description)}\n"
        "---\n"
        "\n"
        f"{GENERATED_NOTICE}\n"
        "\n"
        f"{agent.instructions}\n"
    )


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        temp_path = Path(tmp.name)

    temp_path.replace(path)


def discover_codex_files(selected_agents: set[str]) -> list[Path]:
    if not CODEX_DIR.is_dir():
        raise SyncError(f"Codex agent directory not found: {CODEX_DIR}")

    toml_files = sorted(CODEX_DIR.glob("*.toml"))

    if not toml_files:
        raise SyncError(f"No Codex agent TOML files found in {CODEX_DIR}")

    if not selected_agents:
        return toml_files

    by_name = {path.stem: path for path in toml_files}
    missing = sorted(selected_agents - by_name.keys())
    if missing:
        raise SyncError(
            "Unknown agent(s): "
            + ", ".join(missing)
            + f". Available agents: {', '.join(sorted(by_name))}"
        )

    return [by_name[name] for name in sorted(selected_agents)]


def sync_agent(agent: AgentDefinition, *, check: bool) -> tuple[bool, str]:
    expected = render_claude(agent)
    target = agent.claude_path

    if not target.exists():
        if check:
            return False, f"✗ missing  {target}"

        atomic_write(target, expected)
        return True, f"✓ created  {agent.source_path} -> {target}"

    current = target.read_text(encoding="utf-8").replace("\r\n", "\n")

    if current == expected:
        return True, f"= current  {target}"

    if check:
        return False, f"✗ stale    {target}"

    atomic_write(target, expected)
    return True, f"✓ updated  {agent.source_path} -> {target}"


def generated_claude_files() -> list[Path]:
    if not CLAUDE_DIR.exists():
        return []

    generated: list[Path] = []

    for path in sorted(CLAUDE_DIR.glob("*.agent.md")):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue

        if GENERATED_NOTICE in text:
            generated.append(path)

    return generated


def prune_orphans(
    *,
    valid_agent_stems: set[str],
    check: bool,
) -> tuple[bool, list[str]]:
    ok = True
    messages: list[str] = []

    for path in generated_claude_files():
        agent_name = path.name.removesuffix(".agent.md")

        if agent_name in valid_agent_stems:
            continue

        if check:
            ok = False
            messages.append(f"✗ orphan   {path}")
        else:
            path.unlink()
            messages.append(f"✓ removed  {path}")

    return ok, messages


def main() -> int:
    args = parse_args()

    if args.prune and args.agent:
        print(
            "error: --prune cannot be used together with --agent",
            file=sys.stderr,
        )
        return 2

    selected_agents = set(args.agent)

    try:
        toml_files = discover_codex_files(selected_agents)
        agents = [load_agent(path) for path in toml_files]
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    all_ok = True

    for agent in agents:
        ok, message = sync_agent(agent, check=args.check)
        print(message)
        all_ok = all_ok and ok

    if args.prune:
        try:
            all_codex_stems = {
                path.stem for path in discover_codex_files(set())
            }
        except SyncError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

        prune_ok, messages = prune_orphans(
            valid_agent_stems=all_codex_stems,
            check=args.check,
        )
        for message in messages:
            print(message)

        all_ok = all_ok and prune_ok

    print()

    if args.check:
        if all_ok:
            print(f"✓ {len(agents)} agent definition(s) are synchronized.")
            return 0

        print("✗ Agent definitions are not synchronized.")
        print("  Run: python3 scripts/sync_agents.py")
        return 1

    print(f"✓ Synced {len(agents)} agent definition(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
