#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent

# The script is intended to live under:
#
#   <workspace>/scripts/sync-skills.py
#
WORKSPACE_ROOT = SCRIPT_DIR.parent
CODEX_SKILLS_DIR = WORKSPACE_ROOT / ".codex" / "skills"
CLAUDE_SKILLS_DIR = WORKSPACE_ROOT / ".claude" / "skills"

GENERATED_NOTICE = (
    "<!-- GENERATED FROM .codex/skills BY scripts/sync-skills.py. "
    "DO NOT EDIT THIS FILE DIRECTLY. -->"
)

FRONTMATTER_NAME_RE = re.compile(
    r"(?m)^name:\s*(?:['\"](?P<quoted>[^'\"]+)['\"]|(?P<plain>[^\n#]+?))\s*$"
)


@dataclass(frozen=True)
class SkillDefinition:
    name: str
    source_dir: Path
    source_skill_file: Path

    @property
    def target_dir(self) -> Path:
        return CLAUDE_SKILLS_DIR / self.name

    @property
    def target_skill_file(self) -> Path:
        return self.target_dir / "SKILL.md"


class SyncError(Exception):
    """Raised when canonical skill definitions cannot be safely synchronized."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Synchronize canonical Codex skills into the Claude/Copilot "
            "workspace skill location."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write files. Exit non-zero if generated Claude/Copilot "
            "skill files are missing or stale."
        ),
    )
    parser.add_argument(
        "--skill",
        action="append",
        default=[],
        metavar="NAME",
        help=(
            "Sync/check only the named skill. May be supplied multiple times, "
            "for example: --skill moda-task --skill another-skill."
        ),
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help=(
            "Remove generated Claude/Copilot skill directories that no longer "
            "have a matching canonical Codex skill. Not allowed together with "
            "--skill."
        ),
    )
    return parser.parse_args()


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def parse_frontmatter_name(path: Path, text: str) -> str:
    normalized = normalize_newlines(text)

    if not normalized.startswith("---\n"):
        raise SyncError(f"{path}: SKILL.md must start with YAML frontmatter")

    closing = normalized.find("\n---\n", 4)
    if closing == -1:
        raise SyncError(f"{path}: SKILL.md frontmatter is not closed")

    frontmatter = normalized[4:closing]
    match = FRONTMATTER_NAME_RE.search(frontmatter)

    if not match:
        raise SyncError(f"{path}: frontmatter must contain a non-empty `name`")

    name = (match.group("quoted") or match.group("plain") or "").strip()
    if not name:
        raise SyncError(f"{path}: `name` must be non-empty")

    return name


def render_generated_skill(source_path: Path) -> str:
    text = normalize_newlines(source_path.read_text(encoding="utf-8"))

    if GENERATED_NOTICE in text:
        raise SyncError(
            f"{source_path}: canonical Codex skill already contains the "
            "generated-file notice"
        )

    if not text.startswith("---\n"):
        raise SyncError(f"{source_path}: SKILL.md must start with YAML frontmatter")

    closing = text.find("\n---\n", 4)
    if closing == -1:
        raise SyncError(f"{source_path}: SKILL.md frontmatter is not closed")

    insertion_point = closing + len("\n---\n")

    before = text[:insertion_point]
    after = text[insertion_point:]

    if after.startswith("\n"):
        after = after[1:]

    rendered = (
        before
        + "\n"
        + GENERATED_NOTICE
        + "\n\n"
        + after
    )

    if not rendered.endswith("\n"):
        rendered += "\n"

    return rendered


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        temp_path = Path(tmp.name)

    temp_path.replace(path)


def load_skill(skill_dir: Path) -> SkillDefinition:
    source_skill_file = skill_dir / "SKILL.md"

    if not source_skill_file.is_file():
        raise SyncError(f"{skill_dir}: missing SKILL.md")

    try:
        text = source_skill_file.read_text(encoding="utf-8")
    except OSError as exc:
        raise SyncError(f"{source_skill_file}: unable to read: {exc}") from exc

    frontmatter_name = parse_frontmatter_name(source_skill_file, text)
    expected_name = skill_dir.name

    if frontmatter_name != expected_name:
        raise SyncError(
            f"{source_skill_file}: frontmatter `name` {frontmatter_name!r} "
            f"must match skill directory name {expected_name!r}"
        )

    return SkillDefinition(
        name=expected_name,
        source_dir=skill_dir,
        source_skill_file=source_skill_file,
    )


def discover_skills(selected_skills: set[str]) -> list[SkillDefinition]:
    if not CODEX_SKILLS_DIR.is_dir():
        raise SyncError(f"Codex skill directory not found: {CODEX_SKILLS_DIR}")

    skill_dirs = sorted(
        path
        for path in CODEX_SKILLS_DIR.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    )

    if not skill_dirs:
        raise SyncError(f"No Codex skills found in {CODEX_SKILLS_DIR}")

    by_name = {path.name: path for path in skill_dirs}

    if selected_skills:
        missing = sorted(selected_skills - by_name.keys())
        if missing:
            raise SyncError(
                "Unknown skill(s): "
                + ", ".join(missing)
                + f". Available skills: {', '.join(sorted(by_name))}"
            )

        skill_dirs = [by_name[name] for name in sorted(selected_skills)]

    return [load_skill(path) for path in skill_dirs]


def sync_support_files(
    skill: SkillDefinition,
    *,
    check: bool,
) -> tuple[bool, list[str]]:
    """
    Mirror canonical supporting files for a skill.

    SKILL.md is rendered separately so a generated notice can be inserted
    safely after its YAML frontmatter.

    Supporting files are copied byte-for-byte. Extra target files are not
    removed here; --prune only removes whole generated skill directories whose
    canonical skill no longer exists.
    """
    ok = True
    messages: list[str] = []

    for source in sorted(skill.source_dir.rglob("*")):
        if not source.is_file() or source.name == "SKILL.md":
            continue

        relative = source.relative_to(skill.source_dir)
        target = skill.target_dir / relative

        source_bytes = source.read_bytes()

        if not target.exists():
            if check:
                ok = False
                messages.append(f"✗ missing  {target}")
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(source_bytes)
                messages.append(f"✓ created  {source} -> {target}")
            continue

        target_bytes = target.read_bytes()

        if target_bytes == source_bytes:
            continue

        if check:
            ok = False
            messages.append(f"✗ stale    {target}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(source_bytes)
            messages.append(f"✓ updated  {source} -> {target}")

    return ok, messages


def sync_skill(
    skill: SkillDefinition,
    *,
    check: bool,
) -> tuple[bool, list[str]]:
    expected = render_generated_skill(skill.source_skill_file)
    target = skill.target_skill_file

    ok = True
    messages: list[str] = []

    if not target.exists():
        if check:
            ok = False
            messages.append(f"✗ missing  {target}")
        else:
            atomic_write(target, expected)
            messages.append(
                f"✓ created  {skill.source_skill_file} -> {target}"
            )
    else:
        current = normalize_newlines(target.read_text(encoding="utf-8"))

        if current != expected:
            if check:
                ok = False
                messages.append(f"✗ stale    {target}")
            else:
                atomic_write(target, expected)
                messages.append(
                    f"✓ updated  {skill.source_skill_file} -> {target}"
                )
        else:
            messages.append(f"= current  {target}")

    support_ok, support_messages = sync_support_files(skill, check=check)

    return ok and support_ok, messages + support_messages


def is_generated_skill_dir(path: Path) -> bool:
    skill_file = path / "SKILL.md"

    if not skill_file.is_file():
        return False

    try:
        text = skill_file.read_text(encoding="utf-8")
    except OSError:
        return False

    return GENERATED_NOTICE in text


def generated_claude_skill_dirs() -> list[Path]:
    if not CLAUDE_SKILLS_DIR.exists():
        return []

    return sorted(
        path
        for path in CLAUDE_SKILLS_DIR.iterdir()
        if path.is_dir() and is_generated_skill_dir(path)
    )


def prune_orphans(
    *,
    valid_skill_names: set[str],
    check: bool,
) -> tuple[bool, list[str]]:
    ok = True
    messages: list[str] = []

    for path in generated_claude_skill_dirs():
        if path.name in valid_skill_names:
            continue

        if check:
            ok = False
            messages.append(f"✗ orphan   {path}")
        else:
            shutil.rmtree(path)
            messages.append(f"✓ removed  {path}")

    return ok, messages


def main() -> int:
    args = parse_args()

    if args.prune and args.skill:
        print(
            "error: --prune cannot be used together with --skill",
            file=sys.stderr,
        )
        return 2

    selected_skills = set(args.skill)

    try:
        skills = discover_skills(selected_skills)
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    all_ok = True

    for skill in skills:
        try:
            ok, messages = sync_skill(skill, check=args.check)
        except (OSError, SyncError) as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

        for message in messages:
            print(message)

        all_ok = all_ok and ok

    if args.prune:
        try:
            all_skills = discover_skills(set())
        except SyncError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

        prune_ok, messages = prune_orphans(
            valid_skill_names={skill.name for skill in all_skills},
            check=args.check,
        )

        for message in messages:
            print(message)

        all_ok = all_ok and prune_ok

    print()

    if args.check:
        if all_ok:
            print(f"✓ {len(skills)} skill definition(s) are synchronized.")
            return 0

        print("✗ Skill definitions are not synchronized.")
        print("  Run: python3 scripts/sync-skills.py")
        return 1

    print(f"✓ Synced {len(skills)} skill definition(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
